config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'
  resources :users
  resources :categories
  resources :cards
  resources :items do
    collection do # 新規出品(new用) usl: items/newのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :users, only: [:show] do
    member do
      get 'sign_out', to: 'users#sign_out'
    end
  end

  resources :cards

  resources :items do
    member do
      get 'confirm'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # resources :purchase do
  #   member do
  #     post 'confirm'
  #   end
  #   collection do
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
end

app/views/partials/_banner.html.haml
%aside.ii__appBanner
  .ii__appBanner__inner
    %h2.ii__appBanner__inner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.ii__appBanner__inner__text 今すぐ無料ダウンロード！
    .ii__appBanner__inner__icon
      =link_to "#" do
        = image_tag "material/icon/app-store-icon.svg", class: "ii__appBanner__inner__icon__logo" 
      =link_to "#" do
        = image_tag "material/icon/google-play-icon.svg", class: "ii__appBanner__inner__icon__logo" 

app/views/partials/_footer.html.haml
.ii__footer
  %ul.ii__footer__contents
    %li.ii__footer__contents__content
      %h2.ii__footer__contents__content__head FURIMAについて
      %ul
        %li
          =link_to "会社概要（運営会社）", "#"
        %li
          =link_to "プライバシーポリシー", "#"
        %li
          =link_to "FURIMA利用規約", "#"
        %li
          =link_to "ポイントに関する特約", "#"
    %li.ii__footer__contents__content
      %h2.ii__footer__contents__content__head FURIMAを見る
      %ul
        %li
          =link_to "カテゴリー一覧", "#"
        %li
          =link_to "ブランド一覧", "#"
    %li.ii__footer__contents__content
      %h2.ii__footer__contents__content__head ヘルプ＆ガイド
      %ul
        %li
          =link_to "FURIMAガイド", "#"
        %li
          =link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          =link_to "お知らせ", "#"
  .ii__footer__logo
    =link_to image_tag("material/logo/logo-white.png"), root_path
  %p &copy; FURIMA

app/views/partials/_header.html.haml
.ii__pcHeader
  .ii__pcHeader__headerInner
    .ii__pcHeader__headerInner__mainHeader
      %h1.ii__pcHeader__headerInner__mainHeader__icon
        = link_to image_tag("material/logo/logo.png"), root_path
      .ii__pcHeader__headerInner__mainHeader__searchBox
        %form{"accept-charset": "UTF-8", action: "#", method: "get"}
          %input{name: "utf8", type: "hidden", value: "✓"}
          %input.ii__pcHeader__headerInner__mainHeader__searchBox__input{name: "key", placeholder: "キーワードから探す"}
          %button{type: "submit"}
            .ii__pcHeader__headerInner__mainHeader__searchBox__input__icon
              = image_tag "material/icon/icon-search 1.png" 

    .ii__pcHeader__headerInner__nav
      %ul.ii__pcHeader__headerInner__nav__listLeft
        %li.ii__pcHeader__headerInner__nav__listLeft__item.ii__pcHeader__headerInner__nav__listLeft__first
          = link_to "カテゴリー", "#"
          .ii__pcHeader__headerInner__nav__listLeft__item__tree.displayNone
            %ul.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "レディース", "#", id: "1"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "メンズ", "#", id: "2"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "ベビー・キッズ", "#", id: "3"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "インテリア・住まい・小物", "#", id: "4"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "本・音楽・ゲーム", "#", id: "5"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "おもちゃ・ホビー・グッズ", "#", id: "6"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "コスメ・香水・美容", "#", id: "7"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "家電・スマホ・カメラ", "#", id: "8"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "スポーツ・レジャー", "#", id: "9"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "ハンドメイド", "#", id: "10"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "チケット", "#", id: "11"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "自動車・オートバイ", "#", id: "12"
              %li.ii__pcHeader__headerInner__nav__listLeft__item__tree__categoryTree__categoryTree--item
                = link_to "その他", "#", id: "13"
        %li.ii__pcHeader__headerInner__nav__listLeft__item
          = link_to "ブランド", "#"
      
      - if user_signed_in?
        %ul.ii__pcHeader__headerInner__nav__listRight
          %li.ii__pcHeader__headerInner__nav__listRight__item.ii__pcHeader__headerInner__nav__listRight__item--mypage
            = link_to "マイページ", "/users/#{current_user.id}"
      - else
        %ul.ii__pcHeader__headerInner__nav__listRight
          %li.ii__pcHeader__headerInner__nav__listRight__item.ii__pcHeader__headerInner__nav__listRight__item--login
            = link_to "ログイン", new_user_session_path
          %li.ii__pcHeader__headerInner__nav__listRight__item.ii__pcHeader__headerInner__nav__listRight__item--new
            = link_to "新規会員登録", new_user_registration_path

app/views/partials/_mypage_side.html.haml
.mypage_l-side
  %nav.mypage_l-side__nav
    %ul.mypage_l-side__nav__list
      %li
        = link_to cards_path do
          .mypage_l-side__nav__list__item
            支払い方法
            %i.fas.fa-angle-right
      %li
        = link_to sign_out_user_path do
          .mypage_l-side__nav__list__item
            ログアウト
            %i.fas.fa-angle-right