config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'
  resources :users
  resources :categories
  resources :cards
  resources :items do
    collection do # 新規出品(new用) usl: items/newのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :users, only: [:show] do
    member do
      get 'sign_out', to: 'users#sign_out'
    end
  end

  resources :cards

  resources :items do
    member do
      get 'confirm'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # resources :purchase do
  #   member do
  #     post 'confirm'
  #   end
  #   collection do
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :condition
  belongs_to_active_hash :burden
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :duration

  belongs_to :buyer, class_name: 'User', optional: true
  belongs_to :seller, class_name: 'User'
  belongs_to :category, optional: true

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  # 画像がないと投稿できないようにするバリデーション
  validates_presence_of :images 

  # helperオプションは出品機能が最低限完了し次第、付与。
  # 今はチームメンバーから一部引き継いでいる状態なので、要相談、一旦バリデーションはコメントアウトする
  with_options presence: true do
    validates :name
    validates :price
    validates :discription
    validates :category_id
    validates :condition_id
    validates :burden_id
    validates :prefecture_id
    validates :duration_id
  end

  # showアクションのビューで前の商品を呼び出すメソッド
  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end
 
  # showアクションのビューで後ろの商品を呼び出すメソッド
  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  require 'payjp'
 
  def confirm
    if Card.where(user_id: current_user.id).first.blank?
      redirect_to new_card_path, notice: 'クレジットカードの登録が必要です'
    else
      @user = current_user
      @card = Card.where(user_id: current_user.id).first
      @address = Address.where(user_id: current_user.id).first
      @item = Item.find(params[:id])
    #Payjpの秘密鍵を取得
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    #Payjpから顧客情報を取得し、表示
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @card_information.brand 
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.png"
      when "MasterCard"
        @card_src = "mastercard.png"
      when "American Express"
        @card_src = "americanexpress.png"
      when "Diners Club"
        @card_src = "dinersclub.png"
      when "Discover"
        @card_src = "discover.png"
      end
    end
  end

  def pay
    @item = Item.find(params[:id])
    @card = Card.where(user_id: current_user.id).first

    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    charge = Payjp::Charge.create(
      amount: @item.price,
      customer: Payjp::Customer.retrieve(@card.customer_id),
      currency: 'jpy'
    )
    @buyer = Item.find(params[:id])
    @buyer.update( buyer_id: current_user.id)
    redirect_to done_item_path, notice: '購入が完了しました'

  end

  def done
  end

  # before_action :set_params, only: :create

  def index
    @items = Item.order('created_at DESC').limit(3)
    @images = Image.all
  end

  
  def show
    @item = Item.find(params[:id])
    # 商品画像を取得
    item_id = @item.id
    @images = Image.where("item_id = #{item_id}")
    # 県名を取得
    @item_address = Prefecture.find_by_id(@item.prefecture_id)
    # 商品の状態を取得
    @item_condition = Condition.find_by_id(@item.condition_id)
    # 着払いか元払いかを取得
    @item_burden = Burden.find_by_id(@item.burden_id)
    # 発送までの期間を取得
    @item_duration = Duration.find_by_id(@item.duration_id)
    # 前の商品idを取得
    @p_item = Item.find(params[:id]).previous
    # 後ろの商品idを取得
    @n_item = Item.find(params[:id]).next
  end


  def destroy
    item = Item.find(params[:id])
    item.destroy
    # 一旦root_pathに戻る
    redirect_to root_path
  end


  def new
    @item = Item.new
    # akama/itemモデルに紐づくimageモデルのインスタンス生成
    @item.images.new

    @category_parent_array = ["選択してください"]  
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end
  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    respond_to do |format| 
      format.html
      format.json do
        @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
      end
    end
  end
  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
  #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    respond_to do |format| 
      format.html
      format.json do
        @category_grandchildren = Category.find("#{params[:child_id]}").children
      end
    end
  end

  def create
    @item = Item.new(item_params)
    @category_parent_array = ["選択してください"]  
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    if @item.save
      redirect_to root_path
    else
      @item.images.new
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])

    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: @child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: @grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    
  end

  def update
    @item = Item.find(params[:id])
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  # def set_item
  #   @item = Item.find(params[:id])
  # end

  def item_params
    params.require(:item).permit(:name, :discription, :category_id, :condition_id, :burden_id, :prefecture_id, :duration_id, :price, images_attributes: [:item_image, :_destroy, :id] ).merge(seller_id: current_user.id)
  end 
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/confirm.haml
.ic

  = render partial: "partials/header"

  %main.ic__main
    .ic__main__container
      %h2.ic__main__container__head 購入内容の確認
    .ic__main__flame
      .ic__buy
        .ic__buy__box
          .ic__buy__box__image
            =image_tag(@item.images[0].item_image.url,class:"ic__buy__box__image__tag")
          .ic__buy__box__detail
            %p.ic__buy__box__detail__name
              =@item.name
              %p.ic__buy__box__detail__name__price
                %span
                  = number_to_currency(@item.price,format: "%u%n",unit:"¥",precision: 0)
                %span.ic__buy__box__detail__name__fee
                  （税込）送料込み
      %section.ic__main__container__info
        = form_tag(action: :pay, method: :post) do
          .ic__main__container__info__inner
            %ul.ic__main__container__info__inner__table
              %li.ic__main__container__info__inner__table__row
                .ic__main__container__info__inner__table__head
                  %span 支払い金額
                .ic__main__container__info__inner__table__price
                  %span
                    = number_to_currency(@item.price,format: "%u%n",unit:"¥",precision: 0)
          .ic__main__container__info__inner
            .box
              %h3 支払方法
              .ic__main__container__info__inner__list
                %span クレジットカード
                .ic__main__container__info__inner__list__number
                  = "**** **** **** " + @card_information.last4
                .ic__main__container__info__inner__list__number
                  - exp_month = @card_information.exp_month.to_s
                  - exp_year = @card_information.exp_year.to_s.slice(2,3)
                  = "有効期限 " + exp_month + " / " + exp_year
                = image_tag "material/card_logos/#{@card_src}",alt: @card_brand, id: "card_image", height: "20", width: "30"
          .ic__main__container__info__inner__text
            %h3.distination 配送先
            %address
              = "〒" + @address.postal_code
              %br
              =@address.prefecture_id
              %br
              =@address.city
              =@address.street
              =@address.apartment
              =@address.phone_number
              %br
              =@user.last_name
              =@user.first_name

          %section.ic__main__container__info__inner__bottom
            = submit_tag("購入する", class:"purchase")

  = render partial: "partials/footer"

app/views/items/confirmation.html.haml
.pn__main-container
  = render partial: "partials/header"
  %section.pn__main-container__purchase-details
    %h2.pn__main-container__purchase-details__title
      購入内容の確認
    %section.pn__main-container__purchase-details__item
      .pn__main-container__purchase-details__item__inner
        .pn__main-container__purchase-details__item__inner__product
          %h3.pn__main-container__purchase-details__item__inner__product__image
            = image_tag "#{@item.images[0].item_image}", class:"buy-image", size: "75x75"
          %p.pn__main-container__purchase-details__item__inner__product__name
            商品名
            %br
              = @item.name
        %form.pn__main-container__purchase-details__item__inner__purchase-details
          %p.pn__main-container__purchase-details__item__inner__purchase-details__price
            = @item.price
            %span.pn__main-container__purchase-details__item__inner__purchase-details__price__shipping-fee
              送料込み
          
          %ul.pn__main-container__purchase-details__item__inner__purchase-details__buy-price
            %li.pn__main-container__purchase-details__item__inner__purchase-details__buy-price__box
              .pn__main-container__purchase-details__item__inner__purchase-details__buy-price__box__text
                支払い金額
              .pn__main-container__purchase-details__item__inner__purchase-details__buy-price__box__amount
                %span
                  = @item.price
          %ul.pn__main-container__purchase-details__item__inner__purchase-details__use-points
            %li.pn__main-container__purchase-details__item__inner__purchase-details__use-points__top
              .pn__main-container__purchase-details__item__inner__purchase-details__use-points__top__title
                -# 下記のモデル、テーブル指定は仮置きです。
                = check_box :users, :user_point, {class: "check_box"}, true, false
                ポイントを使用(所持ポイント:P0)

  %section.pn__main-container__purchase-details__user-info
    .pn__main-container__purchase-details__user-info__inner
      %h3
        配送先
      %address.pn__main-container__purchase-details__user-info__inner__address
        %br
        東京都渋谷区道玄坂2丁目23-12 フォンティスビル7F
        %br
          テック太郎
      = link_to "" do
        %span
          変更する
        %i.fas.fa-chevron-right
  %section.pn__main-container__purchase-details__user-pay-info
    .pn__main-container__purchase-details__user-pay-info__inner
      %h3
        支払い方法
      %p.pn__main-container__purchase-details__user-pay-info__inner__text
        %br
        ○○○○-1111-✖️✖️✖️✖️
        %br
        12/30
        %br
        JCB

      = link_to "" do
        %span
          変更する
        %i.fas.fa-chevron-right

  %ul.pn__main-container__purchase-details__item__inner__purchase-details__purchase-button
    = link_to method: :post,class: "submit-btn submit-btn-red" do
      %li.pn__main-container__purchase-details__item__inner__purchase-details__purchase-button__box
        購入する
    = form_with url: purchase_items_path do
      %script.payjp-button{"data-key" => "pk_test_4b1377c49c676a603e23dbc4", :src => "https://checkout.pay.jp", :type => "text/javascript"}
  = render partial: "partials/footer"

app/views/items/done.html.haml
.id

  = render partial: "partials/header"

  .id__notification
    - if flash[:notice]
      = flash[:notice]

  %main.id__container
    .id__container__list
      .id__container__list__btn
        = link_to "トップページへ戻る", root_path

  = render partial: "partials/footer"

app/views/items/edit.html.haml
.in
  = render partial: "partials/header"
  .in__main
    = form_with(model: @item, local:true) do |f|
      = render 'layouts/error_messages', model: f.object
      .items_new-newimage
        .items_new-product__headline
          .items_new-product__headline--title 
            出品画像
            %span.required 必須
        %p.items_new-product__explanation 最大5枚までアップロードできます
        .items_edit-image
          .items_edit-image-box
            .items_edit-content
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  .items_edit-preview-box{"data-index" => "#{i}"}
                    .items_edit-upper-box
                      = image_tag image.item_image.url, width: "100", height: "100", alt: "preview", class: "items_edit-input_images"
                      .items_edit-js-remove
                        削除
              = f.fields_for :images do |image|
                - if @item.persisted?
                  = image.check_box :_destroy, class: "delete-check-box-#{image.index}", style:"display:none;"
            .items_edit-lower-box
              %label.items_edit-lower-box__label
                .items_edit-js-file_group{"data-index" => "#{@item.images.count}"}
                  = f.file_field :item_image, name: "item[images_attributes][#{@item.images.count}][item_image]", id: "items_images_attributes_#{@item.images.count}_item_image", class: 'items_edit-js-file', style: "display:none"


      .in__main__discription
        .in__main__discription__name
          商品名
          %span.required 必須
        = f.text_field :name, class: "in__main__discription__textForm", maxlength: 40, placeholder: "40文字まで"
        .in__main__discription__text
          商品の説明
          %span.required 必須
        = f.text_area :discription, class: "in__main__discription__form", maxlength: 1000, placeholder: "商品の説明(必須 1,000文字以内)\n （色、素材、重さ、定価、注意点など）\n\n例） 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      .in__main__show
        .in__main__show__title
          商品の詳細
        .in__main__show__category
          カテゴリー
          %span.required 必須
          - if @item.category.present?  
            = f.select :parent_id, @category_parent_array,{selected: @item.category.parent.parent.name},{ class: "in__main__show__categoryForm", id: 'parent_category', name: ""}
            = f.select :child_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}),{},{ class: "in__main__show__categoryForm", id: 'child_category', name: ""}
            = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}),{},{ class: "in__main__show__categoryForm", id: 'grandchild_category'}
          - else
            = f.select :category_id, @category_parent_array,{},{ class: "in__main__show__categoryForm", id: 'parent_category', name: ""}

        .in__main__show__condition
          商品の状態
          %span.required 必須
        = f.collection_select :condition_id, Condition.all, :id, :name,{prompt: "選択してください"},{class: "in__main__show__form"}
      .in__main__ship
        .in__main__ship__title
          配送について
        .in__main__ship__charge
          配送料の負担
          %span.required 必須
        = f.collection_select :burden_id, Burden.all, :id, :name,{prompt: "選択してください"},{ class: "in__main__ship__chargeForm"}
        .in__main__ship__region
          発送元の地域
          %span.required 必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name ,{prompt: "選択してください"},{ class: "in__main__ship__regionForm"}
        .in__main__ship__day
          発送までの日数
          %span.required 必須
        = f.collection_select :duration_id, Duration.all, :id, :name,{prompt: "選択してください"},{ class: "in__main__ship__form"}
      .in__main__price
        .in__main__price__title
          価格（¥300〜9,999,999）
        .in__main__price__group
          .in__main__price__group__left
            販売価格
            %span.required 必須
          .in__main__price__group__right
            .in__main__price__group__right__icon ¥
            = f.number_field :price, min: 300, max: 9999999, class: "in__main__price__group__right__form", placeholder: "0"
      .in__main__btn
        = f.submit "更新する", class: "in__main__btn__exhibit"
        = link_to "もどる", root_path, class: "in__main__btn__back"

  = render partial: "partials/footer"

app/views/items/index.html.haml
.ii

  = render partial: "partials/header"

  .ii__main
    %section.ii__main__mainVisual
      .ii__main__mainVisual__content
        %h2.ii__main__mainVisual__content__subtitle
          %br
          人生を変えるフリマアプリ
        %p.ii__main__mainVisual__content__text
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです
        .ii__main__mainVisual__content__btn
          = link_to image_tag("material/icon/app-store-icon.svg"), "#", class: "ii__main__mainVisual__content__btn__aBtn"
          = link_to image_tag("material/icon/google-play-icon.svg"), "#", class: "ii__main__mainVisual__content__btn__gBtn"

    %section.ii__main__topIntroduction
      %h2.ii__main__topIntroduction__subtitle
        FURIMAが選ばれる3つの理由
      %ul.ii__main__topIntroduction__lists
        %li.ii__main__topIntroduction__lists__list
          .ii__main__topIntroduction__lists__list__pict
            %span.ii__main__topIntroduction__lists__list__pict__number 1
            = image_tag "material/pict/pict-reason-01.jpg" 
          %h3.ii__main__topIntroduction__lists__list__text
            %span 3分
            ですぐに出品
          %p.ii__main__topIntroduction__lists__list__description
            スマホで入力するだけで簡単に出品できる！
        %li.ii__main__topIntroduction__lists__list
          .ii__main__topIntroduction__lists__list__pict
            %span.ii__main__topIntroduction__lists__list__pict__number 2
            = image_tag "material/pict/pict-reason-02.jpg" 
          %h3.ii__main__topIntroduction__lists__list__text
            %span シンプル
            で使いやすい
          %p.ii__main__topIntroduction__lists__list__description
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.ii__main__topIntroduction__lists__list.ii__main__topIntroduction__lists__list--last
          .ii__main__topIntroduction__lists__list__pict
            %span.ii__main__topIntroduction__lists__list__pict__number 3
            = image_tag "material/pict/pict-reason-03.jpg" 
          %h3.ii__main__topIntroduction__lists__list__text
            手数料
            %span 業界最安
          %p.ii__main__topIntroduction__lists__list__description
            最大3%でお得に出品&amp;購入！
                
    %section.ii__main__topMiddleDl
      .ii__main__topMiddleDl__inner
        %h2.ii__main__topMiddleDl__inner__subtitle 会員数日本一位
        %p.ii__main__topMiddleDl__inner__text
          FURIMAは、フリマアプリで最も人気。
          %br
          出品・購入回数も業界最多です！
          %br
          ほしかったあの商品に出会えるかもしれません。
        .ii__main__topMiddleDl__inner__btn
          = link_to image_tag("material/icon/app-store-icon.svg"), "#", class: "ii__main__topMiddleDl__inner__btn__aBtn" 
          = link_to image_tag("material/icon/google-play-icon.svg"), "#", class: "ii__main__topMiddleDl__inner__btn__aBtn" 

    %section.ii__main__topKeyFeatures
      %h2.ii__main__topKeyFeatures__head FURIMAの特徴
      .ii__main__topKeyFeatures__items
        %section.ii__main__topKeyFeatures__items__item
          %figure.ii__main__topKeyFeatures__items__item__img
            = image_tag "material/icon/icon-01.png"
          %h3.ii__main__topKeyFeatures__items__item__subtitle 簡単に売り買いできる
          %p.ii__main__topKeyFeatures__items__item__detail
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        %section.ii__main__topKeyFeatures__items__item
          %figure.ii__main__topKeyFeatures__items__item__img
            = image_tag "material/icon/icon-03.png"
          %h3.ii__main__topKeyFeatures__items__item__subtitle 売上金は即日振込みに対応
          %p.ii__main__topKeyFeatures__items__item__detail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %section.ii__main__topKeyFeatures__items__item
          %figure.ii__main__topKeyFeatures__items__item__img
            = image_tag "material/icon/icon-04.png"
          %h3.ii__main__topKeyFeatures__items__item__subtitle 様々な支払いに対応
          %p.ii__main__topKeyFeatures__items__item__detail
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

    %section.ii__main__pickupContainer
      %h2.ii__main__pickupContainer__head ピックアップカテゴリー
      .ii__main__pickupContainer__productBox
        .ii__main__pickupContainer__productBox__productHead
          =link_to "#" do
            %h3.ii__main__pickupContainer__productBox__productHead__title 新規投稿商品
        .ii__main__pickupContainer__productBox__productLists
          - @items.each do |item|
            .ii__main__pickupContainer__productBox__productLists__productList
              = link_to "/items/#{item.id}" do
                %figure.ii__main__pickupContainer__productBox__productLists__productList__productList--img
                  = image_tag @images.find_by(item_id: item.id).item_image.url
                    -if item.buyer_id.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner SOLD
                .ii__main__pickupContainer__productBox__productLists__productList__productList--body
                  %h3.ii__main__pickupContainer__productBox__productLists__productList__productList--body__name
                    %p= "#{item.name}"
                  .ii__main__pickupContainer__productBox__productLists__productList__productList--body__details
                    %ul
                      %li 
                        = "¥#{item.price}"
                    %p (税込)

  = render partial: "partials/banner"

  = render partial: "partials/footer"

  - if user_signed_in?
    = link_to new_item_path do
      .ii__main__purchaseBtn
        %span.ii__main__purchaseBtn__text 出品する
        = image_tag "material/icon/icon_camera.png", class: "ii__main__purchaseBtn__icon"
  - else
    = link_to user_session_path do
      .ii__main__purchaseBtn
        %span.ii__main__purchaseBtn__text 出品する
        = image_tag "material/icon/icon_camera.png", class: "ii__main__purchaseBtn__icon"

app/views/items/new.html.haml
.in
  = render partial: "partials/header"
  .in__main

    = form_with(model: @item, local:true) do |f|
      = render 'layouts/error_messages', model: f.object

      .items_new-newimage
        .items_new-product__headline
          .items_new-product__headline--title 
            出品画像
            %span.required 必須
        %p.items_new-product__explanation 最大5枚までアップロードできます
        .items_new-image
          .items_new-image-box
            .items_new-content
            .items_new-uploader-box
              %label.items_new-uploader__label 
                = f.fields_for :images do |image|
                  .items_newt-js-file_group{"data-index" => "#{@item.images.index}"}
                    = image.file_field :item_image, class: 'items_new-js-file', style: "display:none"
      .in__main__discription
        .in__main__discription__name
          商品名
          %span.required 必須
        = f.text_field :name, class: "in__main__discription__textForm", maxlength: 40, placeholder: "40文字まで"
        .in__main__discription__text
          商品の説明
          %span.required 必須
        = f.text_area :discription, class: "in__main__discription__form", maxlength: 1000, placeholder: "商品の説明(必須 1,000文字以内)\n （色、素材、重さ、定価、注意点など）\n\n例） 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      .in__main__show
        .in__main__show__title
          商品の詳細
        .in__main__show__category
          カテゴリー 
          %span.required 必須
          = f.select :category_id, @category_parent_array,{},{ class: "in__main__show__categoryForm", id: 'parent_category', name: ""}
          -# 初期newアクション時は関係無し、カテゴリー項目以外の不足があった場合の表示
          - if  @category_grandchild_array.present?
            = f.select :category, options_for_select(@category_child_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @item.category.parent.id), {}, {class: 'in__main__show__categoryForm', id: 'child_category'}
            = f.select :category, options_for_select(@category_grandchild_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @item.category.id), {}, {class: 'in__main__show__categoryForm', id: 'grandchild_category'}

        .in__main__show__condition
          商品の状態
          %span.required 必須
        = f.collection_select :condition_id, Condition.all, :id, :name,{prompt: "選択してください"},{ class: "in__main__show__form"}
      .in__main__ship
        .in__main__ship__title
          配送について
        .in__main__ship__charge
          配送料の負担
          %span.required 必須
        = f.collection_select :burden_id, Burden.all, :id, :name,{prompt: "選択してください"},{ class: "in__main__ship__chargeForm"}
        .in__main__ship__region
          発送元の地域
          %span.required 必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name ,{prompt: "選択してください"},{ class: "in__main__ship__regionForm"}
        .in__main__ship__day
          発送までの日数
          %span.required 必須
        = f.collection_select :duration_id, Duration.all, :id, :name,{prompt: "選択してください"},{ class: "in__main__ship__form"}
      .in__main__price
        .in__main__price__title
          価格（¥300〜9,999,999）
        .in__main__price__group
          .in__main__price__group__left
            販売価格
            %span.required 必須
          .in__main__price__group__right
            .in__main__price__group__right__icon ¥
            = f.number_field :price, min: 300, max: 9999999, class: "in__main__price__group__right__form", placeholder: "0"
      .in__main__btn
        = f.submit "出品する", class: "in__main__btn__exhibit"
        = link_to "もどる", root_path, class: "in__main__btn__back"
      
  = render partial: "partials/footer"