config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'
  resources :users
  resources :categories
  resources :cards
  resources :items do
    collection do # 新規出品(new用) usl: items/newのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :users, only: [:show] do
    member do
      get 'sign_out', to: 'users#sign_out'
    end
  end

  resources :cards

  resources :items do
    member do
      get 'confirm'
      post 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # resources :purchase do
  #   member do
  #     post 'confirm'
  #   end
  #   collection do
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :customer_id
    validates :card_id
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def new
    card = Card.where(user_id: current_user.id).first
    redirect_to action: "index" if card.present?
  end

  def create #直前のnewアクションでpayjpからトークンとして返ってきたpayjp-tokenを、customer_idとcard_idとしてデータベースへ保管
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else #customer_idとcard_idを自分たちのデータベースの型に合わせて保管するためにcustomerという変数へ代入
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
      )
      #ここでpayjpのトークンをデータベースの型に合わせて保存
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end


  def index
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "MasterCard"
        @card_src = "mastercard.png"
      when "JCB"
        @card_src = "jcb.png"
      when "American Express"
        @card_src = "americanexpress.png"
      when "Diners Club"
        @card_src = "dinersclub.png"
      when "Discover"
        @card_src = "discover.png"
      end
    end
  end

  def destroy
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.destroy
      redirect_to action: "index", notice: "削除しました"
    else
      redirect_to action: "index", alert: "削除できませんでした"
    end
  end

  private
  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.haml
.ci

  = render partial: "partials/header"

  %main.ci__container
    .ci__title
      %h2 支払い方法
    .ci__card
      %h3 クレジットカード一覧
      - if @card.present?
        %ul
          %li
            .ci__card__list
              %figure
                = image_tag "material/card_logos/#{@card_src}", alt: @card_brand, id: "card_image"
              .ci__card__list__pay
                = "**** **** **** " + @card_information.last4
              .ci__card__list__pay
                - exp_month = @card_information.exp_month.to_s
                - exp_year = @card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              %input{type: "hidden", name: "card_id", value: ""}
              = button_to "削除する", card_path(@card), method: :delete, class:"ci__card__list__delete"
              - if flash[:notice]
                .alert.alert-success
                = flash[:notice]
              - if flash[:alert]
                .alert.alert-dange
                = flash[:alert]
      - else
        .ci__card__new
          .ci__card__new__box
            = link_to new_card_path, class:"ci__card__new__box__btn" do
              %i.far.fa-credit-card 
              クレジットカードを追加する

  = render partial: "partials/footer"

app/views/cards/new.html.haml
.cn

  = render partial: "partials/header"
    
  .cn__notification
    - if flash[:notice]
      = flash[:notice]

  %main.cn__container
    .cn__title
      %h2 クレジットカード情報入力
    .cn__card
      .cn__card__inner
        = form_with url: cards_path, method: :post, html: { name: "inputForm" } do |f|
          .cn__card__inner__head
            = f.label :カード番号, class: 'label'
            %span.blue 必須
            = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
            .image
              = image_tag(image_path('material/card_logos/visa.png'), class: 'image_tag', width: "30", height: "20")
              = image_tag(image_path('material/card_logos/mastercard.png'), class: 'image_tag', width: "30", height: "20")
              = image_tag(image_path('material/card_logos/jcb.png'), class: 'image_tag', width: "30", height: "20")
              = image_tag(image_path('material/card_logos/americanexpress.png'), class: 'image_tag', width: "30", height: "20")
              = image_tag(image_path('material/card_logos/dinersclub.png'), class: 'image_tag', width: "30", height: "20")
              = image_tag(image_path('material/card_logos/discover.png'), class: 'image_tag', width: "30", height: "20")
          .cn__card__inner__expire
            = f.label :有効期限, class: 'label'
            %span.blue 必須
            %br
            .cn__card__inner__expire__wrap
              = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
              %span.expire-text 月
            .cn__card__inner__expire__wrap
              = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029], ["30", 2030]],{} , class: 'input-expire'
              %span.expire-text 年
          .cn__card__inner__security
            = f.label :セキュリティコード, class: 'label'
            %span.blue 必須
            = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"

          -# token_submitを押すと、createアクションへ移る前にJSが発火する
          -# 上の個人情報は、JS内で削除されるが、その代わりにpayjpメソッドによりpayjp-tokenという名のトークンが帰って来る
          -# そのトークンをcn__card__inner__tokenへ埋め込んで、createアクションへ飛ばす
          .content-bottom#cn__card__inner__token
            = f.submit '追加する', class: 'cn__card__inner__token__btn', id: 'token_submit'

  = render partial: "partials/footer"